config/routes.rb
FoodOutlets::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"

  get "logout" => "sessions#destroy", :as => "logout"

  match '/food_outlets', :to => 'pages#food_outlets'

  resources :sessions

  resources :canteens

  resources :outlets

  resources :stalls

  root :to => "pages#home"

end

app/models/canteen.rb
class Canteen < ActiveRecord::Base
  has_many :stalls, :dependent => :destroy
  accepts_nested_attributes_for :stalls, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

end

app/models/outlet.rb
class Outlet < ActiveRecord::Base
end

app/models/stall.rb
class Stall < ActiveRecord::Base
  belongs_to :canteen
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  USER_NAME, PASSWORD = "admin", "password"

  helper_method :admin?

  protected
  def authorize
    unless admin?
      flash[:error] = "Unauthorized access"
      redirect_to food_outlets_path
    false
    end
  end

  def admin?
    session[:user_name] == USER_NAME
    session[:password] == PASSWORD
  end

end

app/controllers/canteens_controller.rb
class CanteensController < ApplicationController
  
  before_filter :authorize, :except => [:show]
  # GET /canteens
  # GET /canteens.xml
  def index
    @canteens = Canteen.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @canteens }
    end
  end

  # GET /canteens/1
  # GET /canteens/1.xml
  def show
    @canteen = Canteen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @canteen }
    end
  end

  # GET /canteens/new
  # GET /canteens/new.xml
  def new
    @canteen = Canteen.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @canteen }
    end
  end

  # GET /canteens/1/edit
  def edit
    @canteen = Canteen.find(params[:id])
  end

  # POST /canteens
  # POST /canteens.xml
  def create
    @canteen = Canteen.new(params[:canteen])

    respond_to do |format|
      if @canteen.save
        format.html { redirect_to(@canteen, :notice => 'Canteen was successfully created.') }
        format.xml  { render :xml => @canteen, :status => :created, :location => @canteen }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @canteen.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /canteens/1
  # PUT /canteens/1.xml
  def update
    @canteen = Canteen.find(params[:id])

    respond_to do |format|
      if @canteen.update_attributes(params[:canteen])
        format.html { redirect_to(@canteen, :notice => 'Canteen was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @canteen.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /canteens/1
  # DELETE /canteens/1.xml
  def destroy
    @canteen = Canteen.find(params[:id])
    @canteen.destroy

    respond_to do |format|
      format.html { redirect_to(canteens_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController

  before_filter :authorize, :except => [:show]
  # GET /outlets
  # GET /outlets.xml
  def index
    @outlets = Outlet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @outlets }
    end
  end

  # GET /outlets/1
  # GET /outlets/1.xml
  def show
    @outlet = Outlet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @outlet }
    end
  end

  # GET /outlets/new
  # GET /outlets/new.xml
  def new
    @outlet = Outlet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @outlet }
    end
  end

  # GET /outlets/1/edit
  def edit
    @outlet = Outlet.find(params[:id])
  end

  # POST /outlets
  # POST /outlets.xml
  def create
    @outlet = Outlet.new(params[:outlet])

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to(@outlet, :notice => 'Outlet was successfully created.') }
        format.xml  { render :xml => @outlet, :status => :created, :location => @outlet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @outlet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /outlets/1
  # PUT /outlets/1.xml
  def update
    @outlet = Outlet.find(params[:id])

    respond_to do |format|
      if @outlet.update_attributes(params[:outlet])
        format.html { redirect_to(@outlet, :notice => 'Outlet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @outlet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /outlets/1
  # DELETE /outlets/1.xml
  def destroy
    @outlet = Outlet.find(params[:id])
    @outlet.destroy

    respond_to do |format|
      format.html { redirect_to(outlets_url) }
      format.xml  { head :ok }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "mPortal"
  end

  def food_outlets
    @title = "Mugs & Grubs"
    @outlets = Outlet.all(:order => 'name')
    @canteens = Canteen.all(:order => 'name')
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:user_name] = params[:user_name]
    session[:password] = params[:password]
    redirect_to food_outlets_path, :notice => "Successfully logged in"
  end

  def destroy
    reset_session
    redirect_to food_outlets_path, :notice => "Successfully logged out"
  end

end

app/controllers/stalls_controller.rb
class StallsController < ApplicationController
  
  before_filter :authorize, :except => [:show]
  # GET /stalls
  # GET /stalls.xml
  def index
    @stalls = Stall.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stalls }
    end
  end

  # GET /stalls/1
  # GET /stalls/1.xml
  def show
    @stall = Stall.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stall }
    end
  end

  # GET /stalls/new
  # GET /stalls/new.xml
  def new
    @stall = Stall.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stall }
    end
  end

  # GET /stalls/1/edit
  def edit
    @stall = Stall.find(params[:id])
  end

  # POST /stalls
  # POST /stalls.xml
  def create
    @stall = Stall.new(params[:stall])

    respond_to do |format|
      if @stall.save
        format.html { redirect_to(@stall, :notice => 'Stall was successfully created.') }
        format.xml  { render :xml => @stall, :status => :created, :location => @stall }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stall.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stalls/1
  # PUT /stalls/1.xml
  def update
    @stall = Stall.find(params[:id])

    respond_to do |format|
      if @stall.update_attributes(params[:stall])
        format.html { redirect_to(@stall, :notice => 'Stall was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stall.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stalls/1
  # DELETE /stalls/1.xml
  def destroy
    @stall = Stall.find(params[:id])
    @stall.destroy

    respond_to do |format|
      format.html { redirect_to(stalls_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canteens_helper.rb
module CanteensHelper
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stalls_helper.rb
module StallsHelper
end

app/views/canteens/_form.html.erb
<%= form_for(@canteen) do |f| %>
  <% if @canteen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canteen.errors.count, "error") %> prohibited this canteen from being saved:</h2>

      <ul>
      <% @canteen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :rows => "3" %>
  </div>
  <div class="field">
    <%= f.label :no_of_stalls %><br />
    <%= f.text_field :no_of_stalls %>
  </div>
  <div class="field">
    <%= f.label :operating_hours %><br />
    <%= f.text_area :operating_hours, :rows => "5" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :announcement %><br />
    <%= f.text_area :announcement, :rows => "5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canteens/edit.html.erb
<% @title= "Editing canteen" %>

<%= render 'form' %>

<%= link_to 'Show', @canteen %> |
<%= link_to 'Back', canteens_path %>

app/views/canteens/index.html.erb
<% @title = "Listing canteens" %>
<div class="evertable">
	<table style="margin-left:5px; margin-right:5px">
		<tr>
			<th>Name</th>
			<th>Location</th>
			<th>No of stalls</th>
			<th>Operating hours</th>
			<th>Image url</th>
			<th>Announcement</th>
			<th>Actions</th>
		</tr>
		<% @canteens.each do |canteen| %>
		<tr>
			<td><%= canteen.name %></td>
			<td><%= canteen.location %></td>
			<td><%= canteen.no_of_stalls %></td>
			<td><%= canteen.operating_hours %></td>
			<td><%= canteen.image_url %></td>
			<td><%= canteen.announcement %></td>
			<td><%= link_to 'Show', canteen %>
			<%= link_to 'Edit', edit_canteen_path(canteen) %>
			<%= link_to 'Destroy', canteen, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
		<% end %>
	</table>
</div>
<br />
<%= link_to 'New Canteen', new_canteen_path %> 

app/views/canteens/new.html.erb
<% @title = "New canteen" %>

<%= render 'form' %>

<%= link_to 'Back', canteens_path %>

app/views/canteens/show.html.erb
<% @title = "Canteen" %>
<div id="content">
	<div class="graytitle">
		<%= @canteen.name %>
	</div>
	<ul class="pageitem">
		<li class="textbox">
			<p>
				<%= image_tag(@canteen.image_url) %>
			</p>
		</li>
		<li class="textbox">
			<span class="name"><%= simple_format(@canteen.location) %></span><span class="ext"></span>
			<br>
			<span class="name"><%= @canteen.no_of_stalls %> stalls</span><span class="ext"></span>
			<br>
			<span class="name"><%= simple_format(@canteen.operating_hours) %></span><span class="ext"></span>
			<!--
			<p>
			<%= simple_format(@canteen.announcement) %>
			</p>
			-->
		</li>
	</ul>
	<% if admin? %>
	<%= link_to 'Edit', edit_canteen_path(@canteen) %> |
	<%= link_to 'Back', canteens_path %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta name="keywords" content="NUS,University,National University of Singapore, students,alumni,parents,family,visitors,computing,administration,campus,faculty,staff,academics,research,libraries,technology,outreach,education,learning,degrees,diversity,teaching,service, Singapore, Asia">
		<meta name="description" content="Unofficial Web Site of the National University of Singapore - a research-intensive university with an entrepreneurial dimension, NUS is ranked consistently as one of the world's top universities.">
		<meta name="viewport" content = "user-scalable=no, width=device-width">
		<link rel="apple-touch-icon" href="../images/icons/Mugs&Grubs.png"/>
		<!--<link rel="apple-touch-icon" href="http://m.ua.edu/i/images/iphone-icon.png">-->
		
		<title>NUS EverMobile Site</title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="nameplate"></div>
		<div id="topbar">
			<div id="title">
				NUS
				<br>
				<%= @title %>
			</div>
			<div class="nav-button right">
				<a class="noeffect" href="search.html"></a>
			</div>
		</div>
		<div id="searchbar">
			<%= link_to "Search", "" %>
		</div>
		<%= yield %>
	</body>
</html>

app/views/outlets/_form.html.erb
<%= form_for(@outlet) do |f| %>
  <% if @outlet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outlet.errors.count, "error") %> prohibited this outlet from being saved:</h2>

      <ul>
      <% @outlet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :rows => "3" %>
  </div>
  <div class="field">
    <%= f.label :operating_hours %><br />
    <%= f.text_area :operating_hours, :rows => "5" %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_area :contact, :rows => "5" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :announcements %><br />
    <%= f.text_area :announcements, :rows => "5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outlets/edit.html.erb
<% @title = "Editing outlet" %>

<%= render 'form' %>

<%= link_to 'Show', @outlet %> |
<%= link_to 'Back', outlets_path %>

app/views/outlets/index.html.erb
<% @title = "Listing outlets" %>
<div class="evertable">
	<table style="margin-left:5px; margin-right:5px">
		<tr>
			<th>Name</th>
			<th>Location</th>
			<th>Operating hours</th>
			<th>Contact</th>
			<th>Image url</th>
			<th>Announcements</th>
			<th>Actions</th>
		</tr>
		<% @outlets.each do |outlet| %>
		<tr>
			<td><%= outlet.name %></td>
			<td><%= outlet.location %></td>
			<td><%= outlet.operating_hours %></td>
			<td><%= outlet.contact %></td>
			<td><%= outlet.image_url %></td>
			<td><%= outlet.announcements %></td>
			<td><%= link_to 'Show', outlet %>
			<%= link_to 'Edit', edit_outlet_path(outlet) %>
			<%= link_to 'Destroy', outlet, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
		<% end %>
	</table>
</div>
<br />
<%= link_to 'New Outlet', new_outlet_path %> 

app/views/outlets/new.html.erb
<% @title = "New outlet" %>

<%= render 'form' %>

<%= link_to 'Back', outlets_path %>

app/views/outlets/show.html.erb
<% @title = "Outlet" %>
<div id="content">
	<div class="graytitle">
		<%= @outlet.name %>
	</div>
	<ul class="pageitem">
		<li class="textbox">
			<p>
				<%= image_tag(@outlet.image_url) %>
			</p>
		</li>
		<li class="textbox">
			<span class="name"><%= simple_format(@outlet.location) %></span><span class="ext"></span>
			<br>
			<span class="name"><%= simple_format(@outlet.operating_hours) %></span><span class="ext"></span>
			<br>
			<span class="name"><%= simple_format(@outlet.contact) %></span><span class="ext"></span>
		</li>
	</ul>
	<p>
		<%= simple_format(@outlet.announcements) %>
	</p>
	<% if admin? %>
	<%= link_to 'Edit', edit_outlet_path(@outlet) %> |
	<%= link_to 'Back', outlets_path %>
	<% end %>
</div>

app/views/pages/food_outlets.html.erb
<%= notice %>
<div class="graytitle">
	Outlets
</div>
<ul class="pageitem">
	<% @outlets.each do |outlet| %>
	<li class="menu">
		<span class="name"><%= link_to outlet.name, outlet %></span>
		<span class="arrow"><%= link_to "", outlet %></span>
	</li>
	<% end %>
</ul>
<div class="graytitle">
	Canteens
</div>
<ul class="pageitem">
	<% @canteens.each do |canteen| %>
	<li class="menu">
		<span class="name"><%= link_to canteen.name, canteen %></span>
		<span class="arrow"><%= link_to "", canteen %></span>
	</li>
	<% end %>
</ul>

app/views/pages/home.html.erb
</div>
<div id="content">
	<div id="menucontent">
		<table class="centered">
			<tbody>
				<tr>
					<td class="three-piece"><a href="http://m.nus.edu.sg/iphone/NativeApps/index.html"><img src="../images/icons/Installer.png" alt="AppStoreHighlights"></a></td>
					<td class="three-piece"><a href="http://m.nus.edu.sg/iphone/Contacts/index.html"><img src="../images/icons/EmergencyContacts_red.png" alt="Useful Contacts"></a></td>
					<td class="three-piece"><a href="https://inetapps.nus.edu.sg/ws/nextsbus/webapp/ShuttleBusTiming/index.html"><img src="../images/icons/bus_arrival_orange.png" alt="Shuttle Bus Information"></a></td>
				</tr>
				<tr>
					<td class="whiteletters">App Store Highlights!</td>
					<td class="whiteletters">Useful Contacts</td>
					<td class="whiteletters">Shuttle Bus Information</td>
				</tr>
				<tr>
					<td class="three-piece"><a href="http://m.nus.edu.sg/iphone/AnnounceNEvents/index.html"><img src="../images/icons/announcements_orange.png" alt="Announcement & Events"></a></td>
					<td class="three-piece"><%= link_to image_tag("../images/icons/Mugs&Grubs.png"), food_outlets_path %></a></td>
					<td class="three-piece"><a href="http://m.nus.edu.sg/iphone/iPhoneProfiles/index.html"><img src="../images/icons/Download.png" alt="iPhone Setup Profiles"></a></td>
				</tr>
				<tr>
					<td class="whiteletters">Announcement & Events </td>
					<td class="whiteletters">Mugs & Grubs</td>
					<td class="whiteletters">iPhone Setup Profiles</td>
				</tr>
				<tr>
					<td class="three-piece"><a href="http://m.nus.edu.sg/mweb/LibrarySubPortal/LibrarySubPortal.html"><img src="../images/icons/library_icon.png" alt="Library"></a></td>
					<td class="three-piece"><a href="http://m.nus.edu.sg/mweb/ROSubPortal/ROSubPortal.html"><img src="../images/icons/ro.png" alt="Registrar's Office"></a></td>
					<td class="three-piece"><a href="FAQ.html"><img src="../images/icons/faq.png" alt="FAQ on iPortal"></a></td>
				</tr>
				<tr>
					<td class="whiteletters">Library</td>
					<td class="whiteletters">Registrar's Office</td>
					<td class="whiteletters">FAQ on iPortal</td>
				</tr>
				<tr>
					<td class="three-piece"><a href="https://www.facebook.com/NationalUniversityofSingapore"><img src="../images/icons/facebook_icon.png" alt="NUS Facebook"></a></td>
					<td class="three-piece"><a href="https://twitter.com/#!/nusosa"><img src="../images/icons/twitter_icon.png" alt="Twitter"></a></td>
					<td class="three-piece"><a href="https://inetapps.nus.edu.sg/ws/staffcontacts/webapp/StaffDirectory/index.html"><img src="../images/icons/staff_directory.png" alt="Staff Directory"></a></td>
				</tr>
				<tr>
					<td class="whiteletters">Facebook</td>
					<td class="whiteletters">Twitter</td>
					<td class="whiteletters">Staff Directory</td>
				</tr>
				<tr>
					<td colspan="3"><!--<img src="./images/ntulogo_temp80.png" alt="logo" />--></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div id="footer">
	<p>
		<b>© 2011  National University of SIngapore</b>
	</p>
	<p>
		Note: If you use GPRS/3G or mobile data plan to access this site, mobile data charges by telcos may apply.
	</p>
</div>

app/views/stalls/_form.html.erb
<%= form_for(@stall) do |f| %>
  <% if @stall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stall.errors.count, "error") %> prohibited this stall from being saved:</h2>

      <ul>
      <% @stall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :rows => "3" %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :food_type %><br />
    <%= f.text_field :food_type %>
  </div>
  <div class="field">
    <%= f.label :operating_hours %><br />
    <%= f.text_area :operating_hours, :rows => "5" %>
  </div>
  <div class="field">
    <%= f.label :price_range %><br />
    <%= f.text_area :price_range, :rows => "1" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :announcement %><br />
    <%= f.text_area :announcement, :rows => "5" %>
  </div>
  <div class="field">
    <%= f.label :canteen_id %><br />
    <%= f.text_field :canteen_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stalls/edit.html.erb
<%= @title = "Editing stall" %>

<%= render 'form' %>

<%= link_to 'Show', @stall %> |
<%= link_to 'Back', stalls_path %>

app/views/stalls/index.html.erb
<% @title = "Listing stalls" %>
<div class="evertable">
	<table style="margin-left:5px; margin-right:5px">
		<tr>
			<th>Name</th>
			<th>Location</th>
			<th>Category</th>
			<th>Food type</th>
			<th>Operating hours</th>
			<th>Price range</th>
			<th>Image url</th>
			<th>Announcement</th>
			<th>Canteen</th>
			<th>Actions</th>
		</tr>
		<% @stalls.each do |stall| %>
		<tr>
			<td><%= stall.name %></td>
			<td><%= stall.location %></td>
			<td><%= stall.category %></td>
			<td><%= stall.food_type %></td>
			<td><%= stall.operating_hours %></td>
			<td><%= stall.price_range %></td>
			<td><%= stall.image_url %></td>
			<td><%= stall.announcement %></td>
			<td><%= stall.canteen %></td>
			<td><%= link_to 'Show', stall %>
			<%= link_to 'Edit', edit_stall_path(stall) %>
			<%= link_to 'Destroy', stall, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
		<% end %>
	</table>
</div>
<br />
<%= link_to 'New Stall', new_stall_path %> 

app/views/stalls/new.html.erb
<% @title = "New stall" %>

<%= render 'form' %>

<%= link_to 'Back', stalls_path %>

app/views/stalls/show.html.erb
<% @title = "Stall" %>
<div id="content">
	<div class="graytitle">
		<%= @stall.name %>
	</div>
	<ul class="pageitem">
		<li class="textbox">
			<p>
				<%= image_tag @stall.image_url %>
			</p>
		</li>
		<li class="textbox">
			<span class="name"><%= @stall.location %></span>
			<span class="ext"></span>
			<br>
			<br>
			<span class="name">Price range: <%= @stall.price_range %></span>
			<span class="ext"></span>
		</li>
	</ul>
	<ul class="pageitem">
		<%= simple_format(@stall.announcement) %>
	</ul>
	<% if admin? %>
	<%= link_to 'Edit', edit_stall_path(@stall) %> |
	<%= link_to 'Back', stalls_path %>
	<% end %>
</div>